name: Release action

on:
  push:
    tags:
      - '*'

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Output comment
        run: echo "This is a comment from the Release action workflow."